INSERT INTO public.team (id, name, "countryOfOrigin", logopath) VALUES (1, 'Mercedes', 'Germany', 'mercedes.jpg');
INSERT INTO public.team (id, name, "countryOfOrigin", logopath) VALUES (2, 'Ferrari', 'Italy', 'ferrari.jpg');
INSERT INTO public.team (id, name, "countryOfOrigin", logopath) VALUES (3, 'Red Bull Racing', 'Austria', 'red_bull.jpg');
INSERT INTO public.team (id, name, "countryOfOrigin", logopath) VALUES (5, 'Toro Rosso', 'Italy', 'toro_rosso.jpg');
INSERT INTO public.team (id, name, "countryOfOrigin", logopath) VALUES (6, 'Renault', 'France', 'renault.jpg');
INSERT INTO public.team (id, name, "countryOfOrigin", logopath) VALUES (7, 'Alfa Romeo Racing', 'Switzerland', 'alfa_romeo.jpg');
INSERT INTO public.team (id, name, "countryOfOrigin", logopath) VALUES (8, 'Racing Point', 'U.K.', 'racing_point.jpg');
INSERT INTO public.team (id, name, "countryOfOrigin", logopath) VALUES (9, 'Haas F1 Team', 'U.S.A.', 'haas.jpg');
INSERT INTO public.team (id, name, "countryOfOrigin", logopath) VALUES (10, 'Williams', 'U.K.', 'williams.jpg');
INSERT INTO public.team (id, name, "countryOfOrigin", logopath) VALUES (4, 'McLaren', 'U.K.', 'mclaren.jpg');
